# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../disenios/archivos.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 400)
        Form.setMinimumSize(QtCore.QSize(800, 400))
        Form.setMaximumSize(QtCore.QSize(800, 400))
        Form.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(imagenes/from-archivos.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"}\n"
"QLabel {\n"
"    background: none;  /* Asegúrate de que los QLabel no tengan fondo */\n"
"}\n"
"QPushButton {\n"
"    background: none;  /* Asegúrate de que los QPushButton no tengan fondo */\n"
"}\n"
"")
        self.line_ruta = QtWidgets.QLineEdit(Form)
        self.line_ruta.setGeometry(QtCore.QRect(20, 80, 691, 31))
        self.line_ruta.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.line_ruta.setObjectName("line_ruta")
        self.boton_agregar = QtWidgets.QPushButton(Form)
        self.boton_agregar.setGeometry(QtCore.QRect(610, 130, 101, 41))
        self.boton_agregar.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.boton_agregar.setText("")
        self.boton_agregar.setObjectName("boton_agregar")
        self.lista_archivos = QtWidgets.QComboBox(Form)
        self.lista_archivos.setGeometry(QtCore.QRect(10, 220, 691, 31))
        self.lista_archivos.setStyleSheet("QComboBox {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.lista_archivos.setObjectName("lista_archivos")
        self.boton_ir_archivo = QtWidgets.QPushButton(Form)
        self.boton_ir_archivo.setGeometry(QtCore.QRect(610, 270, 101, 41))
        self.boton_ir_archivo.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.boton_ir_archivo.setText("")
        self.boton_ir_archivo.setObjectName("boton_ir_archivo")
        self.boton_seleccionar_archivo = QtWidgets.QPushButton(Form)
        self.boton_seleccionar_archivo.setGeometry(QtCore.QRect(20, 130, 241, 41))
        self.boton_seleccionar_archivo.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.boton_seleccionar_archivo.setText("")
        self.boton_seleccionar_archivo.setObjectName("boton_seleccionar_archivo")
        self.boton_eliminar = QtWidgets.QPushButton(Form)
        self.boton_eliminar.setGeometry(QtCore.QRect(480, 270, 101, 41))
        self.boton_eliminar.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.boton_eliminar.setText("")
        self.boton_eliminar.setObjectName("boton_eliminar")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 811, 401))
        self.label_2.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(/home/pepo/PROYECTO FINAL/imagenes/.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"}\n"
"QLabel {\n"
"    background: none;  /* Asegúrate de que los QLabel no tengan fondo */\n"
"}\n"
"QPushButton {\n"
"    background: none;  /* Asegúrate de que los QPushButton no tengan fondo */\n"
"}\n"
"\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imagenes\om-archivos-original.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.line_ruta.raise_()
        self.boton_agregar.raise_()
        self.lista_archivos.raise_()
        self.boton_ir_archivo.raise_()
        self.boton_seleccionar_archivo.raise_()
        self.boton_eliminar.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
