# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../disenios/cambiar_contraseña.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(500, 300)
        Form.setMinimumSize(QtCore.QSize(500, 300))
        Form.setMaximumSize(QtCore.QSize(500, 300))
        Form.setStyleSheet("")
        self.line_contra = QtWidgets.QLineEdit(Form)
        self.line_contra.setGeometry(QtCore.QRect(20, 50, 451, 31))
        self.line_contra.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.line_contra.setObjectName("line_contra")
        self.line_contranueva = QtWidgets.QLineEdit(Form)
        self.line_contranueva.setGeometry(QtCore.QRect(20, 200, 461, 31))
        self.line_contranueva.setStyleSheet("\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.line_contranueva.setObjectName("line_contranueva")
        self.boton_cambiar_contra = QtWidgets.QPushButton(Form)
        self.boton_cambiar_contra.setGeometry(QtCore.QRect(20, 240, 451, 41))
        self.boton_cambiar_contra.setStyleSheet("\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}")
        self.boton_cambiar_contra.setText("")
        self.boton_cambiar_contra.setObjectName("boton_cambiar_contra")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 501, 301))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("imagenes\om-cambiar_contraseña.jpg"))
        self.label_3.setObjectName("label_3")
        self.label_3.raise_()
        self.line_contra.raise_()
        self.line_contranueva.raise_()
        self.boton_cambiar_contra.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
