# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../disenios/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 600)
        Form.setMinimumSize(QtCore.QSize(1000, 600))
        Form.setMaximumSize(QtCore.QSize(1000, 600))
        Form.setStyleSheet("QWidget#centralwidget {\n"
"    background-image: url(imagenes/fondo_secundaria.jpg);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    background-size: cover;\n"
"}")
        self.tabla = QtWidgets.QTableView(Form)
        self.tabla.setGeometry(QtCore.QRect(10, 330, 971, 261))
        self.tabla.setObjectName("tabla")
        self.line_referencia = QtWidgets.QLineEdit(Form)
        self.line_referencia.setGeometry(QtCore.QRect(190, 70, 571, 41))
        self.line_referencia.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.line_referencia.setObjectName("line_referencia")
        self.line_url = QtWidgets.QLineEdit(Form)
        self.line_url.setGeometry(QtCore.QRect(190, 120, 571, 41))
        self.line_url.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.line_url.setObjectName("line_url")
        self.line_contrasena = QtWidgets.QLineEdit(Form)
        self.line_contrasena.setGeometry(QtCore.QRect(190, 170, 571, 41))
        self.line_contrasena.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.line_contrasena.setObjectName("line_contrasena")
        self.boton_ok = QtWidgets.QPushButton(Form)
        self.boton_ok.setGeometry(QtCore.QRect(780, 170, 81, 41))
        self.boton_ok.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.boton_ok.setText("")
        self.boton_ok.setObjectName("boton_ok")
        self.boton_ok_2 = QtWidgets.QPushButton(Form)
        self.boton_ok_2.setGeometry(QtCore.QRect(870, 270, 81, 41))
        self.boton_ok_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.boton_ok_2.setText("")
        self.boton_ok_2.setObjectName("boton_ok_2")
        self.line_clave = QtWidgets.QLineEdit(Form)
        self.line_clave.setGeometry(QtCore.QRect(430, 270, 411, 41))
        self.line_clave.setStyleSheet("QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.line_clave.setObjectName("line_clave")
        self.boton_eliminar = QtWidgets.QPushButton(Form)
        self.boton_eliminar.setGeometry(QtCore.QRect(890, 170, 80, 41))
        self.boton_eliminar.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"")
        self.boton_eliminar.setText("")
        self.boton_eliminar.setObjectName("boton_eliminar")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 1001, 601))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("imagenes\Datos Bancarios.jpg"))
        self.label_2.setObjectName("label_2")
        self.label_2.raise_()
        self.tabla.raise_()
        self.line_referencia.raise_()
        self.line_url.raise_()
        self.line_contrasena.raise_()
        self.boton_ok.raise_()
        self.boton_ok_2.raise_()
        self.line_clave.raise_()
        self.boton_eliminar.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
